export const GET_COMPLAINTS = 'GET_COMPLAINTS';
export const SUCCESSFUL_GET_COMPLAINTS = 'SUCCESSFUL_GET_COMPLAINTS';
export const SUCCESSFUL_CREATE_COMPLAINTS = 'SUCCESSFUL_CREATE_COMPLAINTS';
export const SUCCESSFUL_UPDATE_COMPLAINTS = 'SUCCESSFUL_UPDATE_COMPLAINTS';
export const SUCCESSFUL_DELETE_COMPLAINTS = 'SUCCESSFUL_DELETE_COMPLAINTS';
